symptoms = [
  {"id"=>1, "description"=>"Root", "comment"=>nil, "ancestry"=>nil}, 
  {"id"=>2, "description"=>"Warning Lights are on ", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>3, "description"=>"Check engine", "comment"=>"This is an inspection service. There can be hundreds of reasons for a check engine light to turn on. Mechanic will scan the computer system for diagnostic trouble codes and perform the pin point test and then make repair recommendations.", "ancestry"=>"1/2"}, 
  {"id"=>4, "description"=>"Brake Warning", "comment"=>"This is a brake inspection service. There are different types of brake lights. Mechanic will identify which light is on and then inspect the entire brake system. They will then make recommendation and provide repair estimate.", "ancestry"=>"1/2"}, 
  {"id"=>5, "description"=>"Tire Pressure", "comment"=>"Mechanic will adjust the tire pressure to see if the light goes off. ", "ancestry"=>"1/2"}, 
  {"id"=>6, "description"=>"Battery", "comment"=>"This is an inspection service. This light comes on when there is something wrong with the charging system. Mechanic will perform a battery load test and a charging system test. They will also inspect the condition of the cable. They will then make recommendation and provide repair estimate.", "ancestry"=>"1/2"}, 
  {"id"=>7, "description"=>"Oil Pressure", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations. If the engine oil is low, mechanic will add more oil during this inspection.", "ancestry"=>"1/2"}, 
  {"id"=>8, "description"=>"ABS", "comment"=>"This is an inspection service. Mechanic will scan the car for error codes and check the ABS system for problems. They will then make recommendation and provide repair estimate.", "ancestry"=>"1/2"}, 
  {"id"=>9, "description"=>"Temperature Warning", "comment"=>"This is an inspection service. When this light is on, the car is overheating. Mechanic will identify the problem and make repair recommendations. Otherwise, they will provide you an estimate.", "ancestry"=>"1/2"}, 
  {"id"=>10, "description"=>"Brake Problems", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>11, "description"=>"Brake Pedal is hard to push", "comment"=>"This is an inspection service. Mechanic will inspect the brake system and the EGR valve for carbon (if necessary). They will then make recommendation and provide repair estimate.", "ancestry"=>"1/10"}, 
  {"id"=>12, "description"=>"Car pulls to left or right when I brake", "comment"=>"This is an inspection service. There can be many reasons for this to happen. Mechanic will identify the problem and make repair recommendations. ", "ancestry"=>"1/10"}, 
  {"id"=>13, "description"=>"Brake pedal is lower than usual", "comment"=>"This is an inspection service. Mechanic will inspect the entire brake system. They will then make recommendations and provide repair estimate.", "ancestry"=>"1/10"}, 
  {"id"=>14, "description"=>"Brake Pedal vibrates or shakes", "comment"=>"This is a brake inspection service. Mechanic will check the brake system to see if the rotors or the drums are warped. If the rotors and drums are in good condition, mechanic will then inspect the front suspension.", "ancestry"=>"1/10"}, 
  {"id"=>15, "description"=>"Parking / Emergency Brake does not work", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/10"}, 
  {"id"=>16, "description"=>"Brake safety inspection", "comment"=>"Mechanic will inspect the entire brake system (brake pads, rotors, calipers, master cylinder, fluid, hoses, drums, shoes, proportioning valve, wheel cylinders).", "ancestry"=>"1/10"}, 
  {"id"=>17, "description"=>"Cannot Drive the Car", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>18, "description"=>"Car shuts off when stepping on gas pedal", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/17"}, 
  {"id"=>19, "description"=>"Car does not shift from park to drive", "comment"=>"This is an inspection service. Mechanic will identify the problem and make their repair recommendations.", "ancestry"=>"1/17"}, 
  {"id"=>20, "description"=>"Ignition key does not turn", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/17"}, 
  {"id"=>21, "description"=>"Ignition key is stuck and does not turn", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendation.", "ancestry"=>"1/17"}, 
  {"id"=>22, "description"=>"Heating A/C", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>23, "description"=>"Heater is not working", "comment"=>"This is an inspection service. Mechanic will check the heating system identify the problem and make recommendations.", "ancestry"=>"1/22"}, 
  {"id"=>24, "description"=>"Air is not coming out of vents", "comment"=>"This is an inspection service. Mechanic will inspect the fuses, blower motor switch, blower motor and resistor to identify the problem. If the fuse is blown, mechanic will replace the fuse. If it is not the fuse, they will then make recommendation and provide repair estimate.", "ancestry"=>"1/22"}, 
  {"id"=>25, "description"=>"Windshield fogs up", "comment"=>"This usually happens when the heater core has gone bad. Mechanic will inspect this and provide estimate for repairs. ", "ancestry"=>"1/22"}, 
  {"id"=>26, "description"=>"Rear defroster is not working", "comment"=>"Mechanic will inspect the fuses. If a fuse is blown, they will replace the fuse at no additional cost. If the fuses are ok, then it is likely that the grid is bad. They will make their recommendation at that point.", "ancestry"=>"1/22"}, 
  {"id"=>27, "description"=>"Fan speed control is not working", "comment"=>"This is an inspection service. Mechanic will check the hvac system, identify the problem and make repair recommendations.", "ancestry"=>"1/22"}, 
  {"id"=>28, "description"=>"Problems During Driving", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>29, "description"=>"Steering wheel does not respond properly", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>30, "description"=>"Loss of power", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>31, "description"=>"Smell in the car", "comment"=>"This is an inspection service. There are many possible reasons for your car to have a smell. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>32, "description"=>"Smoke from engine or exhaust", "comment"=>"This is an inspection service. There are many possible reasons for smoke to be coming out of the car. Please do not drive the car and have this inspected asap. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>33, "description"=>"Car pulls in one direction", "comment"=>"This is an inspection service. There can be many reasons for this to happen. Mechanic will identify the problem and make repair recommendations. ", "ancestry"=>"1/28"}, 
  {"id"=>34, "description"=>"Steering wheel does not respond properly", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>35, "description"=>"Loss of power", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>36, "description"=>"Smell in the car", "comment"=>"This is an inspection service. There are many possible reasons for your car to have a smell. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>37, "description"=>"Smoke from engine or exhaust", "comment"=>"This is an inspection service. There are many possible reasons for smoke to be coming out of the car. Please do not drive the car and have this inspected asap. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/28"}, 
  {"id"=>38, "description"=>"Lights", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>39, "description"=>"Headlights are not pointing in the right direction", "comment"=>"This usually happens when the lights go out of adjustment. Mechanic inspect the headlights and adjust them if they are not aligned.", "ancestry"=>"1/38"}, 
  {"id"=>40, "description"=>"High beam is not working", "comment"=>"This is an inspection service. Mechanic will identify the problem and make recommendations.", "ancestry"=>"1/38"}, 
  {"id"=>41, "description"=>"Turn signal light is not working", "comment"=>"This is an inspection service. If the fuse is blown, mechanic will replace the fuse. If it is the bulb or switch, mechanic will provide an estimate for both.", "ancestry"=>"1/38"}, 
  {"id"=>42, "description"=>"Brake light is not working", "comment"=>"This is an inspection service. If the fuse is blown, mechanic will install a new fuse. Otherwise, mechanic will identify the problem and provide repair estimate.", "ancestry"=>"1/38"}, 
  {"id"=>43, "description"=>"Windows", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>44, "description"=>"Window is not going up or down", "comment"=>"This is an inspection service. If the fuse is blown, mechanic will fix it. Otherwise, they will identify the problem and provide recommendation.", "ancestry"=>"1/43"}, 
  {"id"=>45, "description"=>"Window is moving up or down very slowly", "comment"=>"This is an inspection service. Mechanic will identify the problem and provide recommendation.", "ancestry"=>"1/43"}, 
  {"id"=>46, "description"=>"Window Switch is not working", "comment"=>"This is an inspection service. If the fuse is blown, mechanic will replace the fuse. If it is the motor or wiring, mechanic will provide an estimate for both.", "ancestry"=>"1/43"}, 
  {"id"=>47, "description"=>"Other Inspections", "comment"=>nil, "ancestry"=>"1"}, 
  {"id"=>48, "description"=>"Power Outlet is not working", "comment"=>"This is an inspection service. Mechanic will inspect the fuses. If a fuse is blown, they will replace the fuse. If the fuses are ok, then it is likely that the power outlet unit needs to be replaced. They will provide you an estimate for the replacement.", "ancestry"=>"1/47"}, 
  {"id"=>49, "description"=>"Power Mirror is not working", "comment"=>"This is an inspection service. Mechanic will inspect the fuses. If a fuse is blown, they will replace the fuse. If the fuses are ok, then it is likely that the power mirror unit needs to be replaced. They will provide you an estimate for the replacement.", "ancestry"=>"1/47"}, 
  {"id"=>50, "description"=>"Door does not lock or open", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/47"}, 
  {"id"=>51, "description"=>"Trunk does not lock or open", "comment"=>"This is an inspection service. Mechanic will identify the problem and make repair recommendations.", "ancestry"=>"1/47"}, 
  {"id"=>52, "description"=>"Oil/Fluid Leak", "comment"=>"This is an inspection service. Mechanic will first identify which fluid is leaking and find the cause of leak. If it is something simple, they will fix it. If not, they will provide repair estimate.", "ancestry"=>"1/47"}, 
  {"id"=>53, "description"=>"Pre-purchase Car Inspection", "comment"=>"This is a standard 150 point inspection. Mechanic will check all the fluids, hoses, front suspension, brakes, warning lights, interior and exterior lights and body, tires and more. ", "ancestry"=>"1/47"}, 
  {"id"=>54, "description"=>"Seat Belt is not working", "comment"=>"This is an inspection service. The mechanic will identify the problem and provide recommendation.", "ancestry"=>"1/47"}, 
  {"id"=>55, "description"=>"Car Door Lockout", "comment"=>"This is an inspection service. The mechanic will identify the problem and provide recommendation.", "ancestry"=>"1/47"}
]

Symptom.delete_all
symptoms.each do |attrs|
  Symptom.create(attrs)
end
