Time::DATE_FORMATS[:month_year] = "%b %Y"
Time::DATE_FORMATS[:date] = "%d %b %Y (%A)"
Time::DATE_FORMATS[:date_short] = "%d %b %Y"
Time::DATE_FORMATS[:date_abr] = "%a %-d/%-m"
Time::DATE_FORMATS[:date_time] = "%I:%M %p %d %b %Y (%A)"
Time::DATE_FORMATS[:date_time_short] = "%I:%M %p %d %b %Y"
Time::DATE_FORMATS[:time_day_month] = "%l %p %d %b"
